### ISSUE TITLE
Clicking on download without network connection crashes the app

### ISSUE THREAD

**Issue by organik1** [ligi/IPFSDroid#31]
#### Expected behavior

I expected a prompt of failed download, describing that the download had failed due to lack of usable network connection.

#### Actual behavior

Clicking the download button on IPFSDroid when network connection is put off, leads to a crash.

#### How to reproduce

* Download and Install IPFSDroid from Fdroid.org

* Put off data connection on your device and launch IPFSdroid

* On the homepage, locate a button that reads "DOWNLOAD + INIT FULL NODE"

* Click on the button and notice the out come

##### App version: V0.10

Operating system: Android v4.2.2 jellybean

I was also able to replicate this issue on Android v6.0

#### Proof of work

05-11 20:14:20.780 19952-19952/org.ligi.ipfsdroid E/WindowManager: android.view.WindowLeaked: Activity org.ligi.ipfsdroid.MainActivity has leaked window DecorView@5af496f[] that was originally added here at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417) at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331) at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93) at android.app.Dialog.show(Dialog.java:316) at org.ligi.ipfsdroid.IPFSDaemon.download(IPFSDaemon.kt:31) at org.ligi.ipfsdroid.MainActivity$onCreate$1.onClick(MainActivity.kt:31) at android.view.View.performClick(View.java:5610) at android.view.View$PerformClick.run(View.java:22265) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by ligi** [comment]
Thanks for the detailed report!

**Comment by organik1** [comment]
You're most welcome
